name: ouul
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  carousel_slider: ^4.1.1
  lottie:
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
    - assets/images/test_avatar.png
    - assets/images/paws2.png
    - assets/images/Spinner-1s-200px.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      # 코딩 시 사용할 폰트의 이름, family는 동일하지만 다른 사이즈의 폰트를 하나로 묶는다
    - family: Noto_Sans_KR
      fonts:
          # 폰트 아래에 weight나 style을 지정해주면 NotoSansKR 폰트 사용시 fontweight가 w700일 때 NotoSansKR-Thin체를 불러오고, 나머지의 경우에는 NotoSansKR_Regular체를 불러오게 되는 것이다. 
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Black.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Light.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
